apiVersion: v1
kind: Pod
metadata:
  name: nginx-5
  labels:
    env: production
spec:
  containers:
    - name: nginx-5
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: 128Mi
          cpu: "500m"
      env:
        - name: VARIAVEL
          value: VARIAVEL_VALUE
    